[package]
name = "wasm_password_generator"
version = "0.1.1"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.rand]
version = "0.8"
features = ["small_rng"]

[dependencies.getrandom]
version = "0.2.7"
features = ["js"]
